name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        #   - "3.7.1"
        #   - "3.8.0"
        #   - "3.9.0"
        #   - "3.10.0"
        #   - "3.11.0"
          - "3.12.0"
        postgresql-version:
          - "postgres:9.6"
        #   - "postgres:10.0"
        #   - "postgres:11.0"
        #   - "postgres:12.0"
        #   - "postgres:13.0"
        #   - "postgres:14.0"
        #   - "postgres:15.0"
        #   - "postgres:16.0"
        #   - "postgres:17.0"
        ci-extras:
            - ci-psycopg2-sqlalchemy1
            - ci-psycopg2-sqlalchemy2
            - ci-psycopg3-sqlalchemy1
            - ci-psycopg3-sqlalchemy2
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Run PostgreSQL"
        run: |
          ./start-services.sh ${{ matrix.postgresql-version }}

      - name: "Set up Python ${{ matrix.python-version }}"
        run: uv sync --active --group ci --group ${{ matrix.ci-extras }} --no-dev

      - name: "Wait for PostgreSQL"
        run: "timeout 60 bash -c 'until echo > /dev/tcp/127.0.0.1/5432; do sleep 5; done'"

      - name: "Run tests"
        run: |
          python --version
          psql --version
          .venv/bin/pytest --color=yes --durations=20 --cov --cov-report=xml

      - name: "Upload code coverage"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
